language: node_js
node_js:
- "8"
- "7"
- "6"
- "5"
- "10"

os:
- linux
- osx

after_success:
- ./node_modules/codecov/bin/codecov -e TRAVIS_NODE_VERSION
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
- ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < ./coverage/lcov.info

branches:
  only: # whitelist
  - master
  - /^(bugfix|feature|refactor)\/(#\d)?.*$/
