version: 2
jobs:
 build:
   docker:
    - image: circleci/node:6
   environment:
    - NODE_ENV: "test"
   branches:
     only:
       - master
   steps:
    - checkout
    - run:
        name: Install modules
        command: make install
    - run:
        name: Running tests
        command: make test
    - run:
        name: Codecov Coverage
        command: ./node_modules/codecov/bin/codecov
    - run:
        name: Coveralls Coverage
        command: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
    - run:
        name: Codeclimate Coverage
        command: ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < ./coverage/lcov.info
    - run:
        name: Codacy Coverage
        command: ./node_modules/.bin/codacy-coverage < ./coverage/lcov.info
